# Site settings
baseURL = "https://h3-sdpt.firebaseapp.com/"
languageCode = "en-us"
title = "H3"
theme = "H3-Theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
    # You can use Markdown syntax for urls [text](//url.to/source)
    # To create multi-line text in strings use the """example Text""" format
    #
    # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
    # for more icons. The icons are represented by their corresponding
    # CSS class.

    # Provide your metadata here.
    name = "Peter Maida"
    description = "H3 Website"

    # Link custom assets relative to /static
    custom_css = []
    custom_js  = []
    favicon    = "favicon.ico"

    # Just a custom image variable, please define it in .md files for content.
    image = ""

    # 404 error customization
    [params.error404]
        heading = "Page couldn't be found"
        text = "Please visit [this page](/)"

    # Navigation Section
    [params.navigation]
        title = "H3"
        subtitle = "Welcome to H3"
        menu = "Menu"
        logo = "H3 Logo.png"
        home = "#"

        [[params.navigation.links]]
            name = "History"
            url = "history"

        [[params.navigation.links]]
            name = "Start-ups"
            url = "https://new.serendpt.net/startup/"

        [[params.navigation.links]]
            name = "Events"
            url = "events"

        [[params.navigation.links]]
            name = "Spaces"
            url = "spaces"

        [params.navigation.login]
            name = "Login"
            url = "login"



    [[params.carousel]]
        image = "H3 Office.png"
        title = "Welcome to H3"
        description = "Check out our new facility"
        buttontext = ""

    [[params.carousel]]
        image = "algorave.jpg" #https://www.flickr.com/photos/botosynthetic/28547836316/in/photostream/
        title = "Event X"
        description = "Learn what an algorave is"
        buttontext = "Register Here"
        buttonurl = "http://kindohm.github.io/live-coding-presentation/#/"

    [[params.carousel]]
        image = "Full Textile Factory.jpeg"
        title = "Our History"
        description = "This facility began as a church, was a textile factory, and is now a factory for startup companies"
        buttontext = "Learn More"
        buttonurl = "history"

    [[params.carousel]]
        image = "Main Hall.png"
        title = "Spaces"
        description = "This is a space we have"
        buttontext = "Book an Event"
        buttonurl = "events"




  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "example@domain.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    street = "Street"
    city = "City, ST 00000"
    country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Company Name"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com"
      label = "Instagram"

    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
