# Site settings
baseURL = "https://h3-sdpt.firebaseapp.com/"
languageCode = "en-us"
title = "H3"
theme = "H3-Theme"


[params]
    # You can use Markdown syntax for urls [text](//url.to/source)
    # To create multi-line text in strings use the """example Text""" format
    #
    # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
    # for more icons. The icons are represented by their corresponding
    # CSS class.

    # Provide your metadata here.
    name = "Peter Maida"
    description = "H3 Website"

    # Link custom assets relative to /static
    custom_css = []
    custom_js  = []
    favicon    = "favicon.ico"

    # Just a custom image variable, please define it in .md files for content.
    image = ""

    # 404 error customization
    [params.error404]
        heading = "Page couldn't be found"
        text = "Please visit [this page](/)"

    # Navigation Section
    [params.navigation]
        title = "H3"
        subtitle = "Welcome to H3"
        menu = "Menu"
        logo = "H3 Logo.png"
        home = "#"

        [[params.navigation.links]]
            name = "History"
            url = "history"

        [[params.navigation.links]]
            name = "Start-ups"
            url = "https://new.serendpt.net/startup/"
            target = "_blank"

        [[params.navigation.links]]
            name = "Events"
            url = "events"

        [[params.navigation.links]]
            name = "Spaces"
            url = "spaces"

        [params.navigation.login]
            name = "Login"
            url = "login"
